#!/usr/bin/env bash

##

set -e

script_name="$(basename "$0")"
script_dir="$(realpath "$(dirname "$0")")"
script_usage="$script_name"

usage() {
  echo "$script_name: usage: $script_usage" >&2
}

exit_with_error() {
  echo "$script_name: error: $1" >&2
  usage
  exit 1
}

if [ "$#" != "0" ]; then
  exit_with_error "invalid number of arguments, expected \"0\", recieved \"$#\""
fi

##

load_env() {
  IFS=$'\n'
  # shellcheck disable=SC2046
  export $(grep -Ev '^#' "$env_file" | xargs -0)
  IFS=
}

build_images() {
  (
    cd "$1" || exit_with_error "failed to access directory \"$1\""
    docker build -t "$2:latest" .
    docker tag "$2:latest" "$2:$3"
  )
}

##

root_dir="$(realpath "$script_dir/..")"

env_file="$root_dir/.env"

if ! [ -r "$env_file" ]; then
  exit_with_error "failed to read .env file"
fi

load_env

docker_image_name="$DOCKER_IMAGE"

package_version="$("$script_dir/get-version" "$root_dir")"

build_images "$root_dir" "$docker_image_name" "$package_version"