#!/usr/bin/env bash

##

set -e

script_name="$(basename "$0")"
script_dir="$(realpath "$(dirname "$0")")"
script_usage="$script_name [ build | push ]"

usage() {
  echo "$script_name: usage: $script_usage" >&2
}

exit_with_error() {
  echo "$script_name: error: $1" >&2
  usage
  exit 1
}

if [ "$#" != "1" ]; then
  exit_with_error "invalid number of arguments, expected \"1\", recieved \"$#\""
fi

##

docker_build() {
  _script="$script_dir/docker-build"

  if ! "$_script"; then
    exit_with_error "failed to run $_script"
  fi
}

docker_push() {
  _script="$script_dir/docker-push"

  if ! "$_script"; then
    exit_with_error "failed to run $_script"
  fi
}

##

command="$1"

if [ "$command" != "build" ] && [ "$command" != "push" ]; then
  exit_with_error "invalid argument, expected [ build | push ], recieved \"$command\""
fi

if [ "$command" == "build" ]; then
  docker_build
fi

if [ "$command" == "push" ]; then
  docker_push
fi